Import( 'global_env' )

env = global_env.Clone()

env.AppendUnique( CPPPATH = ['#include'] )
env.Append ( CCFLAGS = '-g -Wall' )

src_files = Split( 'util.cpp vector.cpp matrix.cpp quaternion.cpp color.cpp image.cpp ray.cpp intersection.cpp pointLight.cpp areaLight.cpp camera.cpp texture.cpp material.cpp objLoader.cpp mesh.cpp geometry.cpp AABB.cpp scene.cpp rayTracer.cpp main.cpp')

env.Program( '#bin/rayTracer', src_files )
